name: CI - Testes Unificados Agibank

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    name: "🧪 Execução de Testes Full Stack"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Instalar Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Executar Automação (Web, API e Performance)
        run: |
          # 1. Roda Web e API (ignora falhas para seguir adiante)
          mvn clean test -pl teste-blogdoagi,teste-dogapi -fn
          cd teste-performance
          mvn jmeter:jmeter jmeter:results
        continue-on-error: true

      - name: Unificar Resultados Allure
        if: always()
        run: |
          mkdir -p all-results
          find . -type d -name "allure-results" -not -path "./all-results/*" -exec cp -r {}/. all-results/ \;

      - name: Carregar histórico do Allure (gh-pages)
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages-dir

      - name: Allure Report Action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure_report
        with:
          allure_results: "all-results"
          gh_pages: gh-pages-dir
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Integrar Relatório JMeter
        if: always()
        run: |
          # Procura qualquer index.html que não esteja nas pastas do Allure
          REPORT_HTML=$(find . -name "index.html" | grep "jmeter" | head -n 1)
            
          if [ -n "$REPORT_HTML" ]; then
            REPORT_DIR=$(dirname "$REPORT_HTML")
            echo "Relatório encontrado em: $REPORT_DIR"
            
            sudo chmod -R 777 allure-history
            CURRENT_RUN=$(ls -t allure-history | grep -E '^[0-9]+$' | head -n 1)
            
            mkdir -p allure-history/performance
            mkdir -p allure-history/$CURRENT_RUN/performance
            
            cp -r $REPORT_DIR/* allure-history/performance/
            cp -r $REPORT_DIR/* allure-history/$CURRENT_RUN/performance/
          else
            echo "Aviso: Relatório HTML não encontrado. Verifique se a pasta target/jmeter/reports foi criada."
          fi
      - name: Deploy para GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history